<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BloggRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloggRepository extends EntityRepository
{
}
